site_name: Project documentation
docs_dir: docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - content.code.copy
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
exclude_docs: |
  .obsidian/
